version: '3.8'

services:
  redis:
    image: redis:8.0.1
    container_name: redis-lastest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mysql:
    image: mysql:8.0.42
    container_name: mysql-latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: abcd@1234
      MYSQL_DATABASE: Doctor_hehe
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  redis_data:
  mysql_data:
